package me.cobbleBet.visuals;

import me.cobbleBet.Main;
import net.kyori.adventure.text.Component;
import net.kyori.adventure.text.format.NamedTextColor;
import net.kyori.adventure.text.format.TextDecoration;
import org.bukkit.*;
import org.bukkit.entity.*;
import org.bukkit.event.*;
import org.bukkit.event.player.PlayerInteractEntityEvent;
import org.bukkit.event.player.PlayerQuitEvent;
import org.bukkit.persistence.PersistentDataType;
import org.bukkit.inventory.EquipmentSlot;
import org.bukkit.util.Transformation;
import org.joml.Quaternionf;
import org.joml.Vector3f;
import java.util.*;

public final class MinesFieldManager implements Listener {
    private final Main plugin;private final NamespacedKey key;private final Map<String,View> fields=new LinkedHashMap<>();private final Map<String,UUID> activePlayers=new HashMap<>();
    public MinesFieldManager(Main plugin){this.plugin=plugin;this.key=new NamespacedKey(plugin,"mines_field");}
    public void load(){clearAll();for(Map<?,?> row:plugin.getDataStore().getMapList("physicalGames.mines.fields"))try{World world=Bukkit.getWorld(String.valueOf(row.get("world")));Style style=Style.parse(String.valueOf(row.get("style")));Layout layout=Layout.parse(String.valueOf(row.get("layout")));PlayMode mode=PlayMode.parse(String.valueOf(row.get("playMode")));if(world==null||style==null)continue;if(layout==null)layout=Layout.HORIZONTAL;if(mode==null)mode=PlayMode.GUI;float yaw=Math.round((float)num(row.get("yaw"))/22.5f)*22.5f;spawn(new Field(String.valueOf(row.get("id")),new Location(world,num(row.get("x")),num(row.get("y")),num(row.get("z")),yaw,0),style,layout,mode,String.valueOf(row.get("name"))));}catch(RuntimeException e){plugin.getLogger().warning("Skipped an invalid Mines field: "+e.getMessage());}}
    public void create(Player p,String styleName,String layoutName,String modeName,String name){Style style=Style.parse(styleName);Layout layout=Layout.parse(layoutName);PlayMode mode=PlayMode.parse(modeName);if(style==null||layout==null||mode==null){p.sendMessage("§cChoose a valid Mines style, layout, and play mode.");return;}Field field=new Field(nextId(),placement(p),style,layout,mode,name==null||name.isBlank()?"MINES":name.substring(0,Math.min(28,name.length())));spawn(field);save();p.sendMessage("§aCreated Mines field §f"+field.id+"§a.");}
    public boolean moveHere(Player p,String id){View v=find(id);if(v==null)return missing(p,id);replace(v,new Field(v.field.id,placement(p),v.field.style,v.field.layout,v.field.mode,v.field.name));p.sendMessage("§aMoved Mines field §f"+id+"§a.");return true;}
    public boolean moveThere(Player p,String id){View v=find(id);if(v==null)return missing(p,id);Location location=targetPlacement(p);if(location==null){p.sendMessage("§cLook at a block within 30 blocks.");return false;}replace(v,new Field(v.field.id,location,v.field.style,v.field.layout,v.field.mode,v.field.name));p.sendMessage("§aMoved Mines field §f"+id+" §ato the targeted block.");return true;}
    public boolean rotateByDegrees(Player p,String id,float degrees){View v=find(id);if(v==null)return missing(p,id);Location location=v.field.location.clone();location.setYaw(Math.round((location.getYaw()+degrees)/22.5f)*22.5f);replace(v,new Field(v.field.id,location,v.field.style,v.field.layout,v.field.mode,v.field.name));return true;}
    public boolean changeStyle(Player p,String id,String value){View v=find(id);Style style=Style.parse(value);if(v==null)return missing(p,id);if(style==null){p.sendMessage("§cUnknown style.");return false;}replace(v,new Field(v.field.id,v.field.location.clone(),style,v.field.layout,v.field.mode,v.field.name));return true;}
    public boolean changeLayout(Player p,String id,String value){View v=find(id);Layout layout=Layout.parse(value);if(v==null)return missing(p,id);if(layout==null){p.sendMessage("§cChoose horizontal or vertical.");return false;}replace(v,new Field(v.field.id,v.field.location.clone(),v.field.style,layout,v.field.mode,v.field.name));return true;}
    public boolean changeMode(Player p,String id,String value){View v=find(id);PlayMode mode=PlayMode.parse(value);if(v==null)return missing(p,id);if(mode==null){p.sendMessage("§cChoose gui or world.");return false;}activePlayers.remove(v.field.id);replace(v,new Field(v.field.id,v.field.location.clone(),v.field.style,v.field.layout,mode,v.field.name));return true;}
    public boolean rename(Player p,String id,String name){View v=find(id);if(v==null)return missing(p,id);if(name==null||name.isBlank())return false;replace(v,new Field(v.field.id,v.field.location.clone(),v.field.style,v.field.layout,v.field.mode,name.substring(0,Math.min(28,name.length()))));return true;}
    public boolean remove(Player p,String id){View v=find(id);if(v==null)return missing(p,id);v.remove();fields.remove(v.field.id);activePlayers.remove(v.field.id);save();return true;}
    public List<FieldSummary> summaries(){return fields.values().stream().map(v->v.field.summary()).toList();}public FieldSummary summary(String id){View v=find(id);return v==null?null:v.field.summary();}public Set<String> styles(){return new LinkedHashSet<>(Arrays.stream(Style.values()).map(s->s.id).toList());}
    public void clearAll(){fields.values().forEach(View::remove);fields.clear();activePlayers.clear();}
    private void replace(View old,Field field){old.remove();fields.remove(old.field.id);spawn(field);save();}private View find(String id){return id==null?null:fields.get(id.toLowerCase(Locale.ROOT));}private boolean missing(Player p,String id){p.sendMessage("§cNo Mines field exists with ID §f"+id+"§c.");return false;}

    private void spawn(Field field){World world=field.location.getWorld();if(world==null)return;float face=field.location.getYaw()+180;List<Entity> entities=new ArrayList<>();List<BlockDisplay> tiles=new ArrayList<>();
        if(field.layout==Layout.HORIZONTAL){entities.add(block(world,point(field.location,0,.72,0),face,field.style.base,2.9f,.18f,2.9f));entities.add(block(world,point(field.location,0,.84,0),face,field.style.frame,3.04f,.08f,3.04f));for(double x:new double[]{-1.18,1.18})for(double z:new double[]{-1.18,1.18})entities.add(block(world,point(field.location,x,.35,z),face,field.style.leg,.18f,.70f,.18f));}
        else{entities.add(block(world,point(field.location,0,1.72,0),face,field.style.base,2.9f,2.9f,.16f));entities.add(block(world,point(field.location,0,3.20,.01),face,field.style.frame,3.08f,.16f,.28f));entities.add(block(world,point(field.location,0,.24,.01),face,field.style.frame,3.08f,.16f,.28f));for(double x:new double[]{-1.44,1.44})entities.add(block(world,point(field.location,x,1.72,.01),face,field.style.frame,.16f,3.08f,.28f));for(double x:new double[]{-.95,.95}){entities.add(block(world,point(field.location,x,.12,.05),face,field.style.leg,.18f,.24f,.18f));entities.add(block(world,point(field.location,x,.04,.05),face,field.style.frame,.58f,.08f,.44f));}}
        for(int n=0;n<25;n++){final int tileIndex=n;int row=n/5,col=n%5;Location at=field.layout==Layout.HORIZONTAL?point(field.location,(col-2)*.52,.91,(row-2)*.52):point(field.location,(col-2)*.52,1.72+(2-row)*.52,.13);BlockDisplay tile=block(world,at,face,field.style.hidden,.43f,field.layout==Layout.HORIZONTAL?.045f:.43f,field.layout==Layout.HORIZONTAL?.43f:.045f);tiles.add(tile);entities.add(tile);Interaction hit=world.spawn(at,Interaction.class,e->{e.setInteractionWidth(.41f);e.setInteractionHeight(field.layout==Layout.HORIZONTAL?.26f:.41f);e.setResponsive(true);e.setPersistent(false);e.getPersistentDataContainer().set(key,PersistentDataType.STRING,"tile:"+field.id+":"+tileIndex);});entities.add(hit);}
        Location labelAt=field.layout==Layout.HORIZONTAL?point(field.location,0,1.20,1.50):point(field.location,0,3.20,.22);TextDisplay status=text(world,labelAt,face,field.layout==Layout.HORIZONTAL?.40f:.40f);entities.add(status);
        Location cashAt=field.layout==Layout.HORIZONTAL?point(field.location,-1.02,.56,1.68):point(field.location,0,.24,.22);TextDisplay cash=text(world,cashAt,face,field.layout==Layout.HORIZONTAL?.34f:.42f);entities.add(cash);Interaction action=world.spawn(cashAt,Interaction.class,e->{e.setInteractionWidth(field.layout==Layout.HORIZONTAL?1.35f:1.05f);e.setInteractionHeight(field.layout==Layout.HORIZONTAL?.46f:.28f);e.setResponsive(true);e.setPersistent(false);e.getPersistentDataContainer().set(key,PersistentDataType.STRING,(field.mode==PlayMode.WORLD?"cashout:":"open:")+field.id);});entities.add(action);
        if(field.mode==PlayMode.GUI){Interaction open=world.spawn(field.layout==Layout.HORIZONTAL?point(field.location,0,1.02,0):point(field.location,0,1.72,.20),Interaction.class,e->{e.setInteractionWidth(2.85f);e.setInteractionHeight(field.layout==Layout.HORIZONTAL?.30f:2.85f);e.setResponsive(true);e.setPersistent(false);e.getPersistentDataContainer().set(key,PersistentDataType.STRING,"open:"+field.id);});entities.add(open);}
        View view=new View(field,tiles,status,cash,entities);fields.put(field.id,view);reset(view);
    }
    public void update(String id,UUID player,List<Integer>revealed,Set<Integer>mines,double multiplier,boolean started,String result){View v=find(id);if(v==null)return;UUID active=activePlayers.get(id);if(active!=null&&!active.equals(player))return;activePlayers.put(id,player);for(int n=0;n<25;n++)v.tiles.get(n).setBlock((mines.contains(n)?Material.TNT:revealed.contains(n)?v.field.style.safe:v.field.style.hidden).createBlockData());String message=result!=null?result:started?String.format(Locale.US,"RIGHT CLICK TO REVEAL A TILE  •  %.2f×",multiplier):"GETTING THE FIELD READY…";v.status.text(Component.text(message,result==null?v.field.style.accent:NamedTextColor.WHITE).decorate(TextDecoration.BOLD));String actionText=result!=null?"ROUND FINISHED":started?"CASH OUT":"PLEASE WAIT…";v.action.text(Component.text(actionText,result==null?NamedTextColor.WHITE:NamedTextColor.GRAY).decorate(TextDecoration.BOLD));}
    public void finish(String id,UUID player,List<Integer>revealed,Set<Integer>mines,String result){update(id,player,revealed,mines,1,false,"REVEALING THE FIELD…");Bukkit.getScheduler().runTaskLater(plugin,()->{if(player.equals(activePlayers.get(id))){View v=find(id);if(v!=null){v.status.text(Component.text(result,NamedTextColor.WHITE).decorate(TextDecoration.BOLD));v.action.text(Component.text("ROUND FINISHED",NamedTextColor.GRAY).decorate(TextDecoration.BOLD));}}},10L);Bukkit.getScheduler().runTaskLater(plugin,()->{if(player.equals(activePlayers.get(id))){activePlayers.remove(id);View v=find(id);if(v!=null)reset(v);}},70L);}
    public void cancel(String id,UUID player){if(player.equals(activePlayers.get(id))){activePlayers.remove(id);View v=find(id);if(v!=null)reset(v);}}
    private void reset(View v){List<Integer>positions=new ArrayList<>();for(int n=0;n<v.tiles.size();n++)positions.add(n);Collections.shuffle(positions);Set<Integer>mines=new HashSet<>(positions.subList(0,3)),gems=new HashSet<>(positions.subList(3,7));for(int n=0;n<v.tiles.size();n++)v.tiles.get(n).setBlock((mines.contains(n)?Material.TNT:gems.contains(n)?Material.EMERALD_BLOCK:v.field.style.hidden).createBlockData());v.status.text(Component.text(v.field.name,v.field.style.accent).decorate(TextDecoration.BOLD));v.action.text(Component.text("RIGHT CLICK TO PLAY",NamedTextColor.WHITE).decorate(TextDecoration.BOLD));}
    @EventHandler public void interact(PlayerInteractEntityEvent e){if(e.getHand()!=EquipmentSlot.HAND)return;String value=e.getRightClicked().getPersistentDataContainer().get(key,PersistentDataType.STRING);if(value==null)return;e.setCancelled(true);String[] p=value.split(":");if(p.length<2)return;View v=find(p[1]);if(v==null)return;if(v.field.mode==PlayMode.GUI){plugin.minesController.open(e.getPlayer());return;}UUID player=e.getPlayer().getUniqueId(),active=activePlayers.get(v.field.id);if(active==null){if(activePlayers.containsValue(player)){e.getPlayer().sendMessage("§cYou are already using another Mines field.");return;}activePlayers.put(v.field.id,player);plugin.minesController.openPhysical(e.getPlayer(),v.field.id);return;}if(!active.equals(player)){e.getPlayer().sendMessage("§cThis Mines field is already in use.");return;}if(p[0].equals("tile")&&p.length==3)plugin.minesController.tile(e.getPlayer(),Integer.parseInt(p[2]));else if(p[0].equals("cashout"))plugin.minesController.cashout(e.getPlayer());}
    @EventHandler public void quit(PlayerQuitEvent e){UUID player=e.getPlayer().getUniqueId();for(String id:new ArrayList<>(activePlayers.keySet()))if(player.equals(activePlayers.get(id)))cancel(id,player);}
    private BlockDisplay block(World w,Location at,float yaw,Material m,float x,float y,float z){return w.spawn(at,BlockDisplay.class,e->{e.setBlock(m.createBlockData());e.setRotation(yaw,0);e.setPersistent(false);e.setTransformation(new Transformation(new Vector3f(-x/2,-y/2,-z/2),new Quaternionf(),new Vector3f(x,y,z),new Quaternionf()));});}private TextDisplay text(World w,Location at,float yaw,float scale){return w.spawn(at,TextDisplay.class,e->{e.setBillboard(Display.Billboard.FIXED);e.setRotation(yaw,0);e.setAlignment(TextDisplay.TextAlignment.CENTER);e.setLineWidth(420);e.setShadowed(true);e.setBackgroundColor(Color.fromARGB(170,5,8,6));e.setPersistent(false);e.setTransformation(new Transformation(new Vector3f(),new Quaternionf(),new Vector3f(scale),new Quaternionf()));});}
    private Location placement(Player p){Location l=p.getLocation().clone();l.setPitch(0);l.setYaw(Math.round(l.getYaw()/22.5f)*22.5f);l.setY(Math.floor(l.getY())+.03);return l;}private Location targetPlacement(Player p){var target=p.getTargetBlockExact(30,org.bukkit.FluidCollisionMode.NEVER);if(target==null)return null;Location l=target.getLocation().add(.5,1.03,.5);l.setYaw(Math.round(facingYaw(l,p.getLocation())/22.5f)*22.5f);return l;}private float facingYaw(Location from,Location to){return(float)Math.toDegrees(Math.atan2(-(to.getX()-from.getX()),to.getZ()-from.getZ()));}private org.bukkit.util.Vector direction(float yaw){double r=Math.toRadians(yaw);return new org.bukkit.util.Vector(-Math.sin(r),0,Math.cos(r));}private Location point(Location o,double right,double up,double forward){double r=Math.toRadians(o.getYaw());return o.clone().add(-Math.cos(r)*right+Math.sin(r)*forward,up,-Math.sin(r)*right-Math.cos(r)*forward);}private double num(Object v){return v instanceof Number n?n.doubleValue():Double.parseDouble(String.valueOf(v));}private String nextId(){String id;do{id=UUID.randomUUID().toString().substring(0,6).toLowerCase(Locale.ROOT);}while(fields.containsKey(id));return id;}
    private void save(){List<Map<String,Object>> rows=new ArrayList<>();for(View v:fields.values()){Field f=v.field;Map<String,Object> row=new LinkedHashMap<>();row.put("id",f.id);row.put("world",f.location.getWorld().getName());row.put("x",f.location.getX());row.put("y",f.location.getY());row.put("z",f.location.getZ());row.put("yaw",f.location.getYaw());row.put("style",f.style.id);row.put("layout",f.layout.id);row.put("playMode",f.mode.id);row.put("name",f.name);rows.add(row);}plugin.getDataStore().set("physicalGames.mines.fields",rows);}
    private record View(Field field,List<BlockDisplay>tiles,TextDisplay status,TextDisplay action,List<Entity>entities){void remove(){entities.forEach(e->{if(e!=null&&!e.isDead())e.remove();});}}private record Field(String id,Location location,Style style,Layout layout,PlayMode mode,String name){Field{id=id.toLowerCase(Locale.ROOT);}FieldSummary summary(){return new FieldSummary(id,name,style.id,layout.id,mode.id,location.getWorld().getName(),location.getBlockX(),location.getBlockY(),location.getBlockZ());}}public record FieldSummary(String id,String name,String style,String layout,String playMode,String world,int x,int y,int z){public String locationText(){return world+" · "+x+", "+y+", "+z;}}
    private enum Layout{HORIZONTAL("horizontal"),VERTICAL("vertical");final String id;Layout(String id){this.id=id;}static Layout parse(String v){for(Layout x:values())if(x.id.equalsIgnoreCase(v))return x;return null;}}private enum PlayMode{GUI("gui"),WORLD("world");final String id;PlayMode(String id){this.id=id;}static PlayMode parse(String v){for(PlayMode x:values())if(x.id.equalsIgnoreCase(v)||x==WORLD&&"irl".equalsIgnoreCase(v))return x;return null;}}
    private enum Style{CLASSIC("classic",Material.DARK_OAK_PLANKS,Material.POLISHED_BLACKSTONE,Material.GRAY_CONCRETE,Material.EMERALD_BLOCK,Material.DARK_OAK_LOG,NamedTextColor.GOLD),INDUSTRIAL("industrial",Material.DEEPSLATE_TILES,Material.IRON_BLOCK,Material.LIGHT_GRAY_CONCRETE,Material.GOLD_BLOCK,Material.POLISHED_BASALT,NamedTextColor.YELLOW),ROYAL("royal",Material.PURPLE_CONCRETE,Material.GILDED_BLACKSTONE,Material.BLACK_CONCRETE,Material.AMETHYST_BLOCK,Material.POLISHED_BLACKSTONE,NamedTextColor.LIGHT_PURPLE),MODERN("modern",Material.SMOOTH_QUARTZ,Material.CYAN_CONCRETE,Material.WHITE_CONCRETE,Material.DIAMOND_BLOCK,Material.QUARTZ_PILLAR,NamedTextColor.AQUA);final String id;final Material base,frame,hidden,safe,leg;final NamedTextColor accent;Style(String id,Material base,Material frame,Material hidden,Material safe,Material leg,NamedTextColor accent){this.id=id;this.base=base;this.frame=frame;this.hidden=hidden;this.safe=safe;this.leg=leg;this.accent=accent;}static Style parse(String v){for(Style x:values())if(x.id.equalsIgnoreCase(v))return x;return null;}}
}
