name: CobbleBet
version: '${version}'

main: me.cobbleBet.Main
api-version: '1.21'
load: POSTWORLD

commands:
  gamble:
  wallet:
  cobblebet:
permissions:
  cobblebet.admin:
    description: Manage CobbleBet settings and receive plugin update notices.
    default: op
  cobblebet.gamble:
    description: Gamble :D
    default: op
  cobblebet.wallet.admin:
    description: Manage CobbleBet player wallet balances.
    default: op
