package me.cobbleBet.gui;

import com.google.gson.*;
import me.cobbleBet.Main;
import net.kyori.adventure.text.Component;
import net.kyori.adventure.text.format.NamedTextColor;
import net.kyori.adventure.text.format.TextDecoration;
import org.bukkit.*;
import org.bukkit.conversations.*;
import org.bukkit.entity.Player;
import org.bukkit.event.EventHandler;
import org.bukkit.event.Listener;
import org.bukkit.event.inventory.InventoryClickEvent;
import org.bukkit.inventory.*;
import org.bukkit.inventory.meta.ItemMeta;
import org.jetbrains.annotations.NotNull;

import java.text.DecimalFormat;
import java.util.*;

public final class BlackjackController implements Listener {
    private static final DecimalFormat MONEY=new DecimalFormat("#,##0.##");
    private final Main plugin;
    private final Map<UUID,State> states=new HashMap<>();
    public BlackjackController(Main plugin){this.plugin=plugin;}

    public void open(Player player){if(!plugin.requireGameEnabled(player,"blackjack"))return;request(player,"open",null);State state=states.get(player.getUniqueId());if(state!=null&&state.started)renderTable(player,state);else openBetMenu(player);}
    public void openBetMenu(Player player){if(!plugin.requireGameEnabled(player,"blackjack"))return;MenuHolder holder=new MenuHolder(Kind.BET);Inventory inv=Bukkit.createInventory(holder,27,Component.text("Blackjack • Place your bet",NamedTextColor.DARK_GREEN));holder.inventory=inv;fill(inv,Material.BLACK_STAINED_GLASS_PANE);double[] amounts={10,50,100,500,1000};int[] slots={10,11,12,13,14};for(int i=0;i<amounts.length;i++)inv.setItem(slots[i],item(Material.GOLD_INGOT,MONEY.format(amounts[i]),NamedTextColor.GOLD,"Start a hand with this bet."));inv.setItem(16,item(Material.NAME_TAG,"Custom bet",NamedTextColor.AQUA,"Type an amount in chat."));inv.setItem(22,item(Material.BARRIER,"Close",NamedTextColor.RED));player.openInventory(inv);}
    public void start(Player player,String raw){if(!plugin.requireGameEnabled(player,"blackjack"))return;double bet;try{bet=Double.parseDouble(raw.replace(",",""));}catch(NumberFormatException e){player.sendMessage(Component.text("Enter a valid Blackjack bet.",NamedTextColor.RED));return;}if(!Double.isFinite(bet)||bet<.1||bet>1e12||Math.abs(bet*10-Math.round(bet*10))>.001){player.sendMessage(Component.text("Blackjack bets must be at least 0.1 and use one decimal place.",NamedTextColor.RED));return;}states.computeIfAbsent(player.getUniqueId(),key->new State()).result=null;JsonObject extra=new JsonObject();extra.addProperty("bet",bet);extra.addProperty("clientSeed",UUID.randomUUID().toString());request(player,"start",extra);player.closeInventory();player.sendActionBar(Component.text("Dealing your Blackjack hand…",NamedTextColor.GRAY));}
    public void action(Player player,String action){State state=states.get(player.getUniqueId());if((state==null||!state.started)&&!plugin.requireGameEnabled(player,"blackjack"))return;request(player,action,null);player.sendActionBar(Component.text(switch(action){case"hit"->"Drawing a card…";case"stand"->"Dealer is playing…";default->"Doubling your bet…";},NamedTextColor.GRAY));}

    private void request(Player player,String action,JsonObject extra){if(plugin.cobbleSocketClient==null||!plugin.cobbleSocketClient.isApproved()){player.sendMessage(Component.text("CobbleBet is reconnecting. Try again shortly.",NamedTextColor.RED));return;}JsonObject json=extra==null?new JsonObject():extra;json.addProperty("type","blackjackAction");json.addProperty("action",action);json.addProperty("playerUUID",player.getUniqueId().toString());json.addProperty("playerName",player.getName());plugin.cobbleSocketClient.send(json.toString());}

    public void accept(JsonObject message){if(!message.has("playerUUID")||!message.has("event"))return;UUID uuid;try{uuid=UUID.fromString(message.get("playerUUID").getAsString());}catch(RuntimeException e){return;}String event=message.get("event").getAsString();JsonObject data=message.has("data")&&message.get("data").isJsonObject()?message.getAsJsonObject("data"):new JsonObject();Bukkit.getScheduler().runTask(plugin,()->{Player player=Bukkit.getPlayer(uuid);if(player==null)return;State state=states.computeIfAbsent(uuid,key->new State());switch(event){case"error"->player.sendMessage(Component.text(data.has("message")?data.get("message").getAsString():"Blackjack action failed.",NamedTextColor.RED));case"balance-update"->{if(data.has("balance"))state.balance=data.get("balance").getAsDouble();}case"blackjack-ready"->{if(data.has("balance"))state.balance=data.get("balance").getAsDouble();}case"game-state-update"->{state.player=cards(data.getAsJsonArray("playerHand"));state.dealer=cards(data.getAsJsonArray("dealerHand"));state.playerTotal=data.has("playerTotal")?data.get("playerTotal").getAsInt():total(state.player);state.dealerTotal=data.has("dealerTotal")?data.get("dealerTotal").getAsInt():total(state.dealer);state.started=data.has("started")&&data.get("started").getAsBoolean();renderTable(player,state);}case"game-over"->{state.player=cards(data.getAsJsonArray("playerHand"));state.dealer=cards(data.getAsJsonArray("dealerHand"));state.playerTotal=data.has("playerTotal")?data.get("playerTotal").getAsInt():total(state.player);state.dealerTotal=data.has("dealerTotal")?data.get("dealerTotal").getAsInt():total(state.dealer);state.started=false;state.result=data.has("push")&&data.get("push").getAsBoolean()?"Push — your stake was returned":data.has("won")&&data.get("won").getAsBoolean()?"You won "+MONEY.format(data.get("winnings").getAsDouble()):"Dealer wins";renderTable(player,state);player.playSound(player.getLocation(),data.has("won")&&data.get("won").getAsBoolean()?Sound.ENTITY_PLAYER_LEVELUP:Sound.BLOCK_NOTE_BLOCK_BASS,.8f,1f);}default->{}}});}

    private void renderTable(Player player,State state){MenuHolder holder=new MenuHolder(Kind.TABLE);Inventory inv=Bukkit.createInventory(holder,54,Component.text("Blackjack",NamedTextColor.DARK_GREEN));holder.inventory=inv;fill(inv,Material.GREEN_STAINED_GLASS_PANE);String dealerValue=state.started?"?":String.valueOf(state.dealerTotal);inv.setItem(4,item(Material.VILLAGER_SPAWN_EGG,"Dealer • "+dealerValue,NamedTextColor.RED,state.started?"One dealer card remains hidden until the hand ends.":"Dealer hand"));putCards(inv,state.dealer,new int[]{10,11,12,13,14,15,16},state.started);inv.setItem(22,item(Material.GOLD_NUGGET,state.result==null?"Blackjack":state.result,state.result==null?NamedTextColor.GOLD:state.result.startsWith("You won")?NamedTextColor.GREEN:NamedTextColor.YELLOW,"Balance: "+MONEY.format(state.balance)));inv.setItem(31,item(Material.PLAYER_HEAD,player.getName()+" • "+state.playerTotal,NamedTextColor.AQUA));putCards(inv,state.player,new int[]{37,38,39,40,41,42,43},false);if(state.started){inv.setItem(47,item(Material.IRON_SWORD,"Hit",NamedTextColor.YELLOW,"Draw another card."));inv.setItem(49,item(Material.SHIELD,"Stand",NamedTextColor.AQUA,"Keep your hand and play the dealer."));inv.setItem(51,item(Material.DIAMOND,"Double",NamedTextColor.LIGHT_PURPLE,"Double the bet, draw once, then stand."));}else{inv.setItem(49,item(Material.EMERALD,"Play another hand",NamedTextColor.GREEN,"Choose your next bet."));}player.openInventory(inv);}
    private void putCards(Inventory inv,List<Card> cards,int[] slots,boolean hideDealer){for(int i=0;i<cards.size()&&i<slots.length;i++){if(hideDealer&&i==1)inv.setItem(slots[i],item(Material.GRAY_DYE,"Hidden card",NamedTextColor.GRAY));else{Card card=cards.get(i);boolean red=card.suit.equals("♥")||card.suit.equals("♦");inv.setItem(slots[i],item(red?Material.RED_STAINED_GLASS_PANE:Material.WHITE_STAINED_GLASS_PANE,card.rank+card.suit,red?NamedTextColor.RED:NamedTextColor.BLACK));}}}
    private List<Card> cards(JsonArray array){List<Card> cards=new ArrayList<>();if(array!=null)for(JsonElement el:array)try{JsonObject card=el.getAsJsonObject();cards.add(new Card(card.get("rank").getAsString(),card.get("suit").getAsString()));}catch(RuntimeException ignored){}return cards;}
    private int total(List<Card> cards){int value=0,aces=0;for(Card card:cards){if(card.rank.equals("A")){value+=11;aces++;}else if(List.of("J","Q","K").contains(card.rank))value+=10;else try{value+=Integer.parseInt(card.rank);}catch(NumberFormatException ignored){}}while(value>21&&aces-->0)value-=10;return value;}

    @EventHandler public void click(InventoryClickEvent event){if(!(event.getWhoClicked() instanceof Player player)||!(event.getView().getTopInventory().getHolder() instanceof MenuHolder holder))return;event.setCancelled(true);if(event.getClickedInventory()!=event.getView().getTopInventory())return;int slot=event.getRawSlot();if(holder.kind==Kind.BET){if(slot>=10&&slot<=14){double[] amounts={10,50,100,500,1000};start(player,String.valueOf(amounts[slot-10]));}else if(slot==16)custom(player);else if(slot==22)player.closeInventory();}else{State state=states.get(player.getUniqueId());if(state!=null&&state.started){if(slot==47)action(player,"hit");else if(slot==49)action(player,"stand");else if(slot==51)action(player,"double");}else if(slot==49)openBetMenu(player);}}
    private void custom(Player player){player.closeInventory();player.sendMessage(Component.text("Type your Blackjack bet in chat, or type cancel.",NamedTextColor.AQUA));new ConversationFactory(plugin).withLocalEcho(false).withTimeout(30).withFirstPrompt(new StringPrompt(){@Override public @NotNull String getPromptText(@NotNull ConversationContext context){return"";}@Override public Prompt acceptInput(@NotNull ConversationContext context,String input){if(!input.equalsIgnoreCase("cancel"))Bukkit.getScheduler().runTask(plugin,()->start(player,input));return END_OF_CONVERSATION;}}).buildConversation(player).begin();}
    private void fill(Inventory inventory,Material material){ItemStack pane=item(material," ",NamedTextColor.GRAY);for(int i=0;i<inventory.getSize();i++)inventory.setItem(i,pane);}
    private ItemStack item(Material material,String name,NamedTextColor color,String... lore){ItemStack stack=new ItemStack(material);ItemMeta meta=stack.getItemMeta();meta.displayName(Component.text(name,color).decoration(TextDecoration.ITALIC,false));if(lore.length>0)meta.lore(Arrays.stream(lore).map(line->Component.text(line,NamedTextColor.GRAY).decoration(TextDecoration.ITALIC,false)).toList());stack.setItemMeta(meta);return stack;}
    private record Card(String rank,String suit){} private static final class State{List<Card>player=List.of(),dealer=List.of();int playerTotal,dealerTotal;boolean started;double balance;String result;}
    private enum Kind{BET,TABLE} private static final class MenuHolder implements InventoryHolder{final Kind kind;Inventory inventory;MenuHolder(Kind kind){this.kind=kind;}@Override public @NotNull Inventory getInventory(){return inventory;}}
}
