package me.cobbleBet.gui;

import me.cobbleBet.Main;
import me.cobbleBet.players.PlayerWallet;
import me.cobbleBet.storage.WebsiteSettingsStore;
import net.kyori.adventure.text.Component;
import net.kyori.adventure.text.format.NamedTextColor;
import net.kyori.adventure.text.format.TextDecoration;
import org.bukkit.*;
import org.bukkit.configuration.file.FileConfiguration;
import org.bukkit.entity.Player;
import org.bukkit.event.*;
import org.bukkit.event.inventory.*;
import org.bukkit.inventory.*;
import org.bukkit.inventory.meta.*;
import java.util.*;

public final class CobbleMenuController implements Listener {
    private enum Page { HOME, STATS, HEALTH, SETTINGS, GAMES, GAME, APPEARANCE, ECONOMY, PERMISSIONS, VISUALS, ALERTS, WALLET }
    private final Main plugin;
    private final Map<UUID,Page> openPages=new HashMap<>();
    private final Map<UUID,String> confirmations=new HashMap<>();
    private final Map<UUID,String> selectedGames=new HashMap<>();
    private static final String[] GAMES={"mines","blackjack","roulette","coinflip","plinko","dice","crash"};
    private static final String[] THEMES={"classic","pink","cat","viking","ember","harbor","starlight"};
    public record DialogButton(String label,String tooltip,String action,boolean active){}
    public record DialogMenu(String title,String body,List<DialogButton> buttons,String exitLabel){}
    public CobbleMenuController(Main plugin){this.plugin=plugin;}
    public void openDashboard(Player p){open(p,Page.HOME);} public void openWallet(Player p){open(p,Page.WALLET);}
    public void openStats(Player p){open(p,Page.STATS);} public void openHealth(Player p){open(p,Page.HEALTH);}

    private void open(Player p,Page page){if(openNativeDialog(p,page))return;Inventory inv=Bukkit.createInventory(null,page==Page.WALLET?45:54,title(page));decorate(inv);switch(page){case HOME->home(inv,p);case STATS->stats(inv,p);case HEALTH->health(inv);case SETTINGS->settings(inv);case GAMES,GAME->games(inv);case APPEARANCE->appearance(inv);case ECONOMY->economy(inv);case PERMISSIONS->permissions(inv);case VISUALS->visuals(inv);case ALERTS->alerts(inv);case WALLET->wallet(inv,p);}openPages.put(p.getUniqueId(),page);p.openInventory(inv);}
    private boolean openNativeDialog(Player p,Page page){try{Class<?> bridge=Class.forName("me.cobbleBet.gui.NativeDialogMenus",true,plugin.getClass().getClassLoader());return Boolean.TRUE.equals(bridge.getMethod("open",CobbleMenuController.class,Player.class,String.class).invoke(null,this,p,page.name()));}catch(ClassNotFoundException|NoClassDefFoundError|UnsupportedClassVersionError ignored){return false;}catch(ReflectiveOperationException|LinkageError error){plugin.getLogger().fine("Native dialogs unavailable: "+error.getMessage());return false;}}
    private Component title(Page page){return Component.text("CobbleBet  •  "+switch(page){case HOME->"Control center";case STATS->"Server stats";case HEALTH->"Integration health";case SETTINGS->"Settings";case GAMES->"Games";case GAME->"Game settings";case APPEARANCE->"Appearance";case ECONOMY->"Economy";case PERMISSIONS->"Permissions";case VISUALS->"Player visuals";case ALERTS->"Alerts";case WALLET->"Your wallet";},NamedTextColor.DARK_GRAY);}
    private void decorate(Inventory inv){ItemStack glass=item(Material.GRAY_STAINED_GLASS_PANE," ");for(int i=0;i<inv.getSize();i++)if(i<9||i>=inv.getSize()-9||i%9==0||i%9==8)inv.setItem(i,glass);}
    private void home(Inventory i,Player p){i.setItem(13,head(p,"Hello, "+p.getName(),"Your server owner tools"));i.setItem(20,item(Material.COMPARATOR,"Server settings","Games, appearance, economy, permissions,","alerts, and player visuals."));i.setItem(22,item(Material.WRITABLE_BOOK,"Server statistics","Wallets, players, and activity."));i.setItem(24,item(Material.RECOVERY_COMPASS,"Integration health","Connection, economy, updater, and heartbeat."));i.setItem(31,item(Material.BELL,"Alerts","Choose important owner warnings."));i.setItem(33,item(Material.ENDER_EYE,"Open web owner panel","Receive your private clickable panel link."));}
    private void stats(Inventory i,Player p){double total=Main.playerWalletHashMap.values().stream().mapToDouble(PlayerWallet::getBalance).sum();int active=plugin.gamblingIndicatorManager==null?0:plugin.gamblingIndicatorManager.getActiveWebPlayerCount();i.setItem(19,item(Material.PLAYER_HEAD,"Players online",String.valueOf(Bukkit.getOnlinePlayers().size())));i.setItem(21,item(Material.EMERALD,"Actively gambling",String.valueOf(active),"Players with a focused CobbleBet game page"));i.setItem(23,item(Material.GOLD_INGOT,"Wallet value",format(total),"Across "+Main.playerWalletHashMap.size()+" saved wallets"));i.setItem(25,item(Material.CLOCK,"Server uptime",duration(System.currentTimeMillis()-plugin.getStartedAt())));back(i);}
    private void health(Inventory i){boolean connected=plugin.cobbleSocketClient!=null&&plugin.cobbleSocketClient.isApproved();i.setItem(19,state(connected,"CobbleBet connection",connected?"Connected":"Disconnected"));i.setItem(21,item(Material.NAME_TAG,"Plugin version",plugin.getDescription().getVersion()));i.setItem(23,state(plugin.getEconomyManager()!=null,"Economy adapter",Main.economyType+" · "+(Main.economyType.equalsIgnoreCase("item")?Main.economyItem:Main.vaultCurrencyName)));i.setItem(25,state(Main.autoUpdateEnabled,"Automatic updates",Main.autoUpdateEnabled?"Enabled":"Disabled"));i.setItem(31,item(Material.CLOCK,"Last status sent",plugin.getLastStatusAt()==0?"Waiting":new Date(plugin.getLastStatusAt()).toString()));back(i);}
    private void settings(Inventory i){i.setItem(19,item(Material.DIAMOND_SWORD,"Games","Availability and extra house edge"));i.setItem(21,item(Material.PAINTING,"Appearance","Theme and maintenance mode"));i.setItem(23,item(Material.GOLD_INGOT,"Economy","Currency and wallet cap"));i.setItem(25,item(Material.TRIPWIRE_HOOK,"Permissions","Command permission requirements"));i.setItem(30,item(Material.FIREWORK_STAR,"Player visuals","Animations, sounds, and motion"));i.setItem(32,item(Material.BELL,"Alerts & broadcasts","Warnings and big wins"));back(i);}
    private void games(Inventory i){FileConfiguration c=plugin.getConfig();int[] slots={19,20,21,22,23,24,25};for(int n=0;n<GAMES.length;n++){String game=GAMES[n];boolean on=c.getBoolean("websiteCustomization.enabledGames."+game,true);double edge=c.getDouble("websiteCustomization.gameRules."+game+".percent",0);i.setItem(slots[n],state(on,pretty(game),(on?"Available":"Disabled")+" · Extra edge "+edge+"%","Left click: toggle","Right click: +0.5% · Shift-right: -0.5%"));}back(i);}
    private void appearance(Inventory i){String current=plugin.getConfig().getString("websiteCustomization.theme","classic");for(int n=0;n<THEMES.length;n++)i.setItem(19+n,state(THEMES[n].equals(current),pretty(THEMES[n]),THEMES[n].equals(current)?"Selected":"Click to select"));boolean maintenance=plugin.getConfig().getBoolean("websiteCustomization.maintenance.enabled",false);i.setItem(31,state(!maintenance,"Maintenance mode",maintenance?"New games are paused":"Games are open","Click to toggle"));back(i);}
    private void economy(Inventory i){i.setItem(20,state(Main.economyType.equalsIgnoreCase("vault"),"Vault economy",Main.economyType.equalsIgnoreCase("vault")?"Active":"Click to select"));i.setItem(22,state(Main.economyType.equalsIgnoreCase("item"),"Item economy",Main.economyType.equalsIgnoreCase("item")?"Active · "+Main.economyItem:"Click to select"));i.setItem(24,item(Material.CHEST,"Maximum wallet balance",format(Main.maximumBalance),"Left click: +100,000","Right click: -100,000"));back(i);}
    private void permissions(Inventory i){String[] keys={"gamble","admin","walletAdmin"},names={"/gamble","/cobblebet admin tools","/wallet set"};for(int n=0;n<keys.length;n++)i.setItem(20+n*2,state(Main.isPermissionRequired(keys[n]),names[n],Main.isPermissionRequired(keys[n])?"Permission required":"Open to everyone","Click to toggle"));back(i);}
    private void visuals(Inventory i){toggleItem(i,19,"gamblingVisuals.enabled","Gambling animation");toggleItem(i,21,"gamblingVisuals.sounds","Animation sounds");toggleItem(i,23,"gamblingVisuals.screenTitles","Result titles");toggleItem(i,25,"gamblingVisuals.actionBar","Action bar");toggleItem(i,30,"gamblingVisuals.visibleToNearbyPlayers","Nearby player effects");toggleItem(i,32,"gamblingVisuals.reducedMotion","Reduced motion");back(i);}
    private void alerts(Inventory i){toggleItem(i,20,"websiteCustomization.ownerAlerts.connection","Connection alerts");toggleItem(i,22,"websiteCustomization.ownerAlerts.economy","Economy failure alerts");toggleItem(i,24,"websiteCustomization.ownerAlerts.transactions","Transaction alerts");toggleItem(i,30,"websiteCustomization.ownerAlerts.updates","Update alerts");toggleItem(i,32,"broadcastingEnabled","Big win broadcasts");back(i);}
    private void wallet(Inventory i,Player p){i.setItem(13,head(p,"Wallet balance",format(plugin.getEconomyManager().getBalance(p))+" "+currency()));i.setItem(20,item(Material.HOPPER,"Deposit 1","Uses Vault money or your inventory."));i.setItem(21,item(Material.HOPPER,"Deposit 16","Uses Vault money or your inventory."));i.setItem(22,item(Material.ENDER_CHEST,"Deposit 64 from Ender Chest","Item economy only. Removes the configured", "item directly from your Ender Chest."));i.setItem(24,item(Material.DROPPER,"Withdraw 1","Returns funds to the server economy."));i.setItem(25,item(Material.DROPPER,"Withdraw 16"));i.setItem(26,item(Material.DROPPER,"Withdraw 64"));i.setItem(31,item(Material.BOOK,"How deposits work",Main.economyType.equalsIgnoreCase("item")?"Inventory deposits remove "+Main.economyItem+".":"Vault deposits use your server balance.","The Ender Chest button only uses that chest."));}

    public DialogMenu dialogMenu(Player p,String pageName){
        Page page;
        try{page=Page.valueOf(pageName.toUpperCase(Locale.ROOT));}catch(IllegalArgumentException error){page=Page.HOME;}
        List<DialogButton> buttons=new ArrayList<>();
        String title="CobbleBet · "+switch(page){case HOME->"Control center";case STATS->"Server statistics";case HEALTH->"Integration health";case SETTINGS->"Server settings";case GAMES->"Games";case GAME->pretty(selectedGames.getOrDefault(p.getUniqueId(),"mines"));case APPEARANCE->"Appearance";case ECONOMY->"Economy";case PERMISSIONS->"Permissions";case VISUALS->"Player visuals";case ALERTS->"Alerts & broadcasts";case WALLET->"Your wallet";};
        String body;
        switch(page){
            case HOME->{body="Welcome, "+p.getName()+". Choose what you want to manage.";buttons.add(db("Server settings","Games, appearance, economy, permissions and visuals.","page:SETTINGS"));buttons.add(db("Server statistics","Players, wallet totals and active gamblers.","page:STATS"));buttons.add(db("Integration health","Connection, economy, updater and heartbeat.","page:HEALTH"));buttons.add(db("Alerts","Owner warnings and big win broadcasts.","page:ALERTS"));buttons.add(db("Open web owner panel","Send your private owner panel link in chat.","request-panel"));}
            case STATS->{double total=Main.playerWalletHashMap.values().stream().mapToDouble(PlayerWallet::getBalance).sum();int active=plugin.gamblingIndicatorManager==null?0:plugin.gamblingIndicatorManager.getActiveWebPlayerCount();body="Players online: "+Bukkit.getOnlinePlayers().size()+"\nActively gambling: "+active+"\nSaved wallets: "+Main.playerWalletHashMap.size()+"\nWallet value: "+format(total)+"\nUptime: "+duration(System.currentTimeMillis()-plugin.getStartedAt());buttons.add(db("Refresh","Refresh these live server statistics.","page:STATS"));buttons.add(db("Back","Return to the control center.","page:HOME"));}
            case HEALTH->{boolean connected=plugin.cobbleSocketClient!=null&&plugin.cobbleSocketClient.isApproved();body="CobbleBet: "+(connected?"Connected":"Disconnected")+"\nPlugin version: "+plugin.getDescription().getVersion()+"\nEconomy: "+Main.economyType+" · "+currency()+"\nAutomatic updates: "+(Main.autoUpdateEnabled?"Enabled":"Disabled")+"\nLast status: "+(plugin.getLastStatusAt()==0?"Waiting":new Date(plugin.getLastStatusAt()).toString());buttons.add(db("Refresh","Refresh connection information.","page:HEALTH"));buttons.add(db("Back","Return to the control center.","page:HOME"));}
            case SETTINGS->{body="Choose a section. Changes are saved to the plugin configuration.";buttons.add(db("Games","Availability and extra house edge.","page:GAMES"));buttons.add(db("Appearance","Player website theme and maintenance mode.","page:APPEARANCE"));buttons.add(db("Economy","Currency provider and wallet cap.","page:ECONOMY"));buttons.add(db("Permissions","Choose which commands require permissions.","page:PERMISSIONS"));buttons.add(db("Player visuals","Animations, sounds, titles and motion.","page:VISUALS"));buttons.add(db("Alerts & broadcasts","Owner warnings and big wins.","page:ALERTS"));buttons.add(db("Back","Return to the control center.","page:HOME"));}
            case GAMES->{body="Choose a game to manage its availability and extra house edge.";for(String game:GAMES){boolean on=plugin.getConfig().getBoolean("websiteCustomization.enabledGames."+game,true);double edge=plugin.getConfig().getDouble("websiteCustomization.gameRules."+game+".percent",0);buttons.add(new DialogButton((on?"✓ ":"✕ ")+pretty(game),(on?"Available":"Disabled")+" · Extra house edge: "+edge+"%.","game-open:"+game,on));}buttons.add(db("Back","Return to server settings.","page:SETTINGS"));}
            case GAME->{String game=selectedGames.getOrDefault(p.getUniqueId(),"mines");boolean on=plugin.getConfig().getBoolean("websiteCustomization.enabledGames."+game,true);double edge=plugin.getConfig().getDouble("websiteCustomization.gameRules."+game+".percent",0);body=pretty(game)+" is "+(on?"available":"disabled")+".\nExtra house edge: "+edge+"%\n\nThe edge is only applied when it is above 0%.";buttons.add(new DialogButton(on?"✓ Game enabled":"✕ Game disabled","Click to "+(on?"disable":"enable")+" this game.","game-toggle:"+game,on));buttons.add(db("Increase edge by 0.5%","Increase this game's extra house edge.","game-edge-up:"+game));buttons.add(db("Decrease edge by 0.5%","Decrease this game's extra house edge.","game-edge-down:"+game));buttons.add(db("Back to games","Choose another game.","page:GAMES"));}
            case APPEARANCE->{String current=plugin.getConfig().getString("websiteCustomization.theme","classic");body="Choose the look players see when they play from this server.";for(String theme:THEMES)buttons.add(new DialogButton((theme.equals(current)?"✓ ":"")+pretty(theme),theme.equals(current)?"Currently selected":"Use this website theme.","theme:"+theme,theme.equals(current)));boolean maintenance=plugin.getConfig().getBoolean("websiteCustomization.maintenance.enabled",false);buttons.add(new DialogButton(maintenance?"✕ Maintenance enabled":"✓ Games are open",maintenance?"Click to reopen games.":"Click to pause new games.","maintenance",!maintenance));buttons.add(db("Back","Return to server settings.","page:SETTINGS"));}
            case ECONOMY->{body="Current economy: "+Main.economyType+"\nCurrency: "+currency()+"\nMaximum wallet: "+format(Main.maximumBalance);buttons.add(new DialogButton((Main.economyType.equalsIgnoreCase("vault")?"✓ ":"")+"Vault economy","Use the server's Vault economy.","economy:vault",Main.economyType.equalsIgnoreCase("vault")));buttons.add(new DialogButton((Main.economyType.equalsIgnoreCase("item")?"✓ ":"")+"Item economy","Use "+Main.economyItem+" from player inventories.","economy:item",Main.economyType.equalsIgnoreCase("item")));buttons.add(db("Wallet cap +100,000","Increase the maximum wallet balance.","economy:max-up"));buttons.add(db("Wallet cap -100,000","Decrease the maximum wallet balance.","economy:max-down"));buttons.add(db("Back","Return to server settings.","page:SETTINGS"));}
            case PERMISSIONS->{body="When disabled, every player can use that command. Permission changes require a second click.";String[] keys={"gamble","admin","walletAdmin"},names={"/gamble","Owner tools","/wallet set"};for(int n=0;n<keys.length;n++){boolean required=Main.isPermissionRequired(keys[n]);boolean pending=("permission:"+keys[n]).equals(confirmations.get(p.getUniqueId()));String label=pending?"Confirm change: "+names[n]:(required?"✓ Required: ":"✕ Open: ")+names[n];buttons.add(new DialogButton(label,pending?"Click again to confirm this safety-sensitive change.":required?"Players need the permission node.":"Every player can use this command.","permission:"+keys[n],required));}buttons.add(db("Back","Return to server settings.","page:SETTINGS"));}
            case VISUALS->{body="Control the Minecraft animation shown while players gamble on the website.";addToggle(buttons,"Gambling animation","gamblingVisuals.enabled");addToggle(buttons,"Animation sounds","gamblingVisuals.sounds");addToggle(buttons,"Result titles","gamblingVisuals.screenTitles");addToggle(buttons,"Action bar","gamblingVisuals.actionBar");addToggle(buttons,"Nearby player effects","gamblingVisuals.visibleToNearbyPlayers");addToggle(buttons,"Reduced motion","gamblingVisuals.reducedMotion");buttons.add(db("Back","Return to server settings.","page:SETTINGS"));}
            case ALERTS->{body="Choose which events notify owners and whether large wins are broadcast.";addToggle(buttons,"Connection alerts","websiteCustomization.ownerAlerts.connection");addToggle(buttons,"Economy failure alerts","websiteCustomization.ownerAlerts.economy");addToggle(buttons,"Transaction alerts","websiteCustomization.ownerAlerts.transactions");addToggle(buttons,"Update alerts","websiteCustomization.ownerAlerts.updates");addToggle(buttons,"Big win broadcasts","broadcastingEnabled");buttons.add(db("Back","Return to the control center.","page:HOME"));}
            case WALLET->{double balance=plugin.getEconomyManager().getBalance(p);body="Balance: "+format(balance)+" "+currency()+"\n"+(Main.economyType.equalsIgnoreCase("item")?"Deposits remove "+Main.economyItem+" from your inventory or Ender Chest.":"Deposits and withdrawals use your server economy balance.");buttons.add(db("Deposit 1","Move 1 into your CobbleBet wallet.","wallet:deposit:1"));buttons.add(db("Deposit 16","Move 16 into your CobbleBet wallet.","wallet:deposit:16"));if(Main.economyType.equalsIgnoreCase("item"))buttons.add(db("Deposit 64 from Ender Chest","Remove 64 "+Main.economyItem+" directly from your Ender Chest.","wallet:ender:64"));buttons.add(db("Withdraw 1","Return 1 to the server economy.","wallet:withdraw:1"));buttons.add(db("Withdraw 16","Return 16 to the server economy.","wallet:withdraw:16"));buttons.add(db("Withdraw 64","Return 64 to the server economy.","wallet:withdraw:64"));buttons.add(db("Refresh balance","Refresh your wallet total.","page:WALLET"));}
            default->throw new IllegalStateException("Unexpected menu page");
        }
        return new DialogMenu(title,body,List.copyOf(buttons),"Close");
    }

    private DialogButton db(String label,String tooltip,String action){return new DialogButton(label,tooltip,action,false);}
    private void addToggle(List<DialogButton> buttons,String label,String path){boolean on=plugin.getConfig().getBoolean(path,true);buttons.add(new DialogButton((on?"✓ ":"✕ ")+label,on?"Enabled. Click to disable.":"Disabled. Click to enable.","toggle:"+path,on));}

    public boolean isWalletDialogAction(String action){return action!=null&&(action.equalsIgnoreCase("page:WALLET")||action.toLowerCase(Locale.ROOT).startsWith("wallet:"));}
    public void handleDialogAction(Player p,String rawAction){
        String action=rawAction==null?"":rawAction;
        if(action.startsWith("page:")){try{open(p,Page.valueOf(action.substring(5).toUpperCase(Locale.ROOT)));}catch(IllegalArgumentException ignored){}return;}
        if(action.equals("request-panel")){requestPanel(p);return;}
        if(action.equals("maintenance")){String path="websiteCustomization.maintenance.enabled";plugin.getConfig().set(path,!plugin.getConfig().getBoolean(path,false));saveWebsite();open(p,Page.APPEARANCE);return;}
        if(action.startsWith("theme:")){String theme=action.substring(6);if(Arrays.asList(THEMES).contains(theme)){plugin.getConfig().set("websiteCustomization.theme",theme);saveWebsite();}open(p,Page.APPEARANCE);return;}
        if(action.startsWith("game-open:")){String game=action.substring(10);if(Arrays.asList(GAMES).contains(game)){selectedGames.put(p.getUniqueId(),game);open(p,Page.GAME);}return;}
        if(action.startsWith("game-toggle:")||action.startsWith("game-edge-up:")||action.startsWith("game-edge-down:")){String game=action.substring(action.indexOf(':')+1);if(Arrays.asList(GAMES).contains(game)){selectedGames.put(p.getUniqueId(),game);if(action.startsWith("game-toggle:")){String path="websiteCustomization.enabledGames."+game;plugin.getConfig().set(path,!plugin.getConfig().getBoolean(path,true));}else{String path="websiteCustomization.gameRules."+game+".percent";double change=action.startsWith("game-edge-up:")?.5:-.5;plugin.getConfig().set(path,Math.max(0,Math.min(50,plugin.getConfig().getDouble(path,0)+change)));}saveWebsite();}open(p,Page.GAME);return;}
        if(action.startsWith("economy:")){String choice=action.substring(8);if(choice.equals("vault")||choice.equals("item"))plugin.getConfig().set("economyType",choice);else if(choice.equals("max-up"))plugin.getConfig().set("maximumBalance",Main.maximumBalance+100000);else if(choice.equals("max-down"))plugin.getConfig().set("maximumBalance",Math.max(100000,Main.maximumBalance-100000));saveGeneral();open(p,Page.ECONOMY);return;}
        if(action.startsWith("permission:")){String key=action.substring(11);if(!Arrays.asList("gamble","admin","walletAdmin").contains(key))return;String confirmation="permission:"+key;if(!confirmation.equals(confirmations.remove(p.getUniqueId()))){confirmations.put(p.getUniqueId(),confirmation);open(p,Page.PERMISSIONS);return;}plugin.getConfig().set("permissions."+key,!Main.isPermissionRequired(key));saveGeneral();open(p,Page.PERMISSIONS);return;}
        if(action.startsWith("toggle:")){String path=action.substring(7);List<String> allowed=List.of("gamblingVisuals.enabled","gamblingVisuals.sounds","gamblingVisuals.screenTitles","gamblingVisuals.actionBar","gamblingVisuals.visibleToNearbyPlayers","gamblingVisuals.reducedMotion","websiteCustomization.ownerAlerts.connection","websiteCustomization.ownerAlerts.economy","websiteCustomization.ownerAlerts.transactions","websiteCustomization.ownerAlerts.updates","broadcastingEnabled");if(!allowed.contains(path))return;flip(path);if(path.startsWith("websiteCustomization"))WebsiteSettingsStore.load(plugin);open(p,path.startsWith("gamblingVisuals")?Page.VISUALS:Page.ALERTS);return;}
        if(action.startsWith("wallet:")){String[] parts=action.split(":");if(parts.length!=3)return;double amount;try{amount=Double.parseDouble(parts[2]);}catch(NumberFormatException error){return;}boolean ok=switch(parts[1]){case "deposit"->plugin.getEconomyManager().deposit(p,amount);case "ender"->plugin.getEconomyManager().depositFromEnderChest(p,(int)amount);case "withdraw"->plugin.getEconomyManager().withdraw(p,amount);default->false;};p.sendActionBar(Component.text(ok?"Wallet updated.":"That transaction could not be completed.",ok?NamedTextColor.GREEN:NamedTextColor.RED));open(p,Page.WALLET);}
    }

    @EventHandler public void click(InventoryClickEvent e){if(!(e.getWhoClicked() instanceof Player p))return;Page page=openPages.get(p.getUniqueId());if(page==null)return;e.setCancelled(true);if(e.getClickedInventory()!=e.getView().getTopInventory())return;int slot=e.getRawSlot();if((slot==45&&page!=Page.HOME)||(slot==36&&page==Page.WALLET)){open(p,Page.HOME);return;}switch(page){case HOME->{if(slot==20)open(p,Page.SETTINGS);else if(slot==22)open(p,Page.STATS);else if(slot==24)open(p,Page.HEALTH);else if(slot==31)open(p,Page.ALERTS);else if(slot==33)requestPanel(p);}case SETTINGS->{if(slot==19)open(p,Page.GAMES);else if(slot==21)open(p,Page.APPEARANCE);else if(slot==23)open(p,Page.ECONOMY);else if(slot==25)open(p,Page.PERMISSIONS);else if(slot==30)open(p,Page.VISUALS);else if(slot==32)open(p,Page.ALERTS);}case GAMES,GAME->gameClick(p,slot,e.isRightClick(),e.isShiftClick());case APPEARANCE->appearanceClick(p,slot);case ECONOMY->economyClick(p,slot,e.isRightClick());case PERMISSIONS->permissionClick(p,slot);case VISUALS->visualClick(p,slot);case ALERTS->alertClick(p,slot);case WALLET->walletClick(p,slot);default->{}}}
    private void gameClick(Player p,int slot,boolean right,boolean shift){int n=index(new int[]{19,20,21,22,23,24,25},slot);if(n<0)return;String game=GAMES[n];if(right){String path="websiteCustomization.gameRules."+game+".percent";double edge=plugin.getConfig().getDouble(path,0)+(shift?-.5:.5);plugin.getConfig().set(path,Math.max(0,Math.min(50,edge)));}else{String path="websiteCustomization.enabledGames."+game;plugin.getConfig().set(path,!plugin.getConfig().getBoolean(path,true));}saveWebsite();open(p,Page.GAMES);}
    private void appearanceClick(Player p,int slot){if(slot>=19&&slot<19+THEMES.length){plugin.getConfig().set("websiteCustomization.theme",THEMES[slot-19]);saveWebsite();}else if(slot==31){String path="websiteCustomization.maintenance.enabled";plugin.getConfig().set(path,!plugin.getConfig().getBoolean(path,false));saveWebsite();}open(p,Page.APPEARANCE);}
    private void economyClick(Player p,int slot,boolean right){if(slot==20)plugin.getConfig().set("economyType","vault");else if(slot==22)plugin.getConfig().set("economyType","item");else if(slot==24)plugin.getConfig().set("maximumBalance",Math.max(100000,Main.maximumBalance+(right?-100000:100000)));else return;saveGeneral();open(p,Page.ECONOMY);}
    private void permissionClick(Player p,int slot){String key=slot==20?"gamble":slot==22?"admin":slot==24?"walletAdmin":null;if(key==null)return;String confirmation="permission:"+key;if(!confirmation.equals(confirmations.remove(p.getUniqueId()))){confirmations.put(p.getUniqueId(),confirmation);p.sendActionBar(Component.text("Click again to confirm this permission change.",NamedTextColor.YELLOW));return;}plugin.getConfig().set("permissions."+key,!Main.isPermissionRequired(key));saveGeneral();open(p,Page.PERMISSIONS);}
    private void visualClick(Player p,int slot){String path=switch(slot){case 19->"gamblingVisuals.enabled";case 21->"gamblingVisuals.sounds";case 23->"gamblingVisuals.screenTitles";case 25->"gamblingVisuals.actionBar";case 30->"gamblingVisuals.visibleToNearbyPlayers";case 32->"gamblingVisuals.reducedMotion";default->null;};if(path!=null){flip(path);open(p,Page.VISUALS);}}
    private void alertClick(Player p,int slot){String path=switch(slot){case 20->"websiteCustomization.ownerAlerts.connection";case 22->"websiteCustomization.ownerAlerts.economy";case 24->"websiteCustomization.ownerAlerts.transactions";case 30->"websiteCustomization.ownerAlerts.updates";case 32->"broadcastingEnabled";default->null;};if(path!=null){flip(path);if(path.startsWith("websiteCustomization"))WebsiteSettingsStore.load(plugin);open(p,Page.ALERTS);}}
    private void walletClick(Player p,int slot){boolean ok;if(slot==20)ok=plugin.getEconomyManager().deposit(p,1);else if(slot==21)ok=plugin.getEconomyManager().deposit(p,16);else if(slot==22)ok=plugin.getEconomyManager().depositFromEnderChest(p,64);else if(slot==24)ok=plugin.getEconomyManager().withdraw(p,1);else if(slot==25)ok=plugin.getEconomyManager().withdraw(p,16);else if(slot==26)ok=plugin.getEconomyManager().withdraw(p,64);else return;p.sendActionBar(Component.text(ok?"Wallet updated.":"That transaction could not be completed.",ok?NamedTextColor.GREEN:NamedTextColor.RED));open(p,Page.WALLET);}
    private void requestPanel(Player p){if(plugin.cobbleSocketClient==null||!plugin.cobbleSocketClient.isApproved()){p.sendActionBar(Component.text("CobbleBet is not connected.",NamedTextColor.RED));return;}com.google.gson.JsonObject request=new com.google.gson.JsonObject();request.addProperty("type","requestAdminPanel");request.addProperty("playerUUID",p.getUniqueId().toString());request.addProperty("playerName",p.getName());plugin.pendingAdminPanelRequests.put(p.getUniqueId(),System.currentTimeMillis()+30000);plugin.cobbleSocketClient.send(request.toString());p.closeInventory();p.sendMessage(Component.text("Requesting your private CobbleBet owner panel link…",NamedTextColor.GRAY));}
    private void flip(String path){plugin.getConfig().set(path,!plugin.getConfig().getBoolean(path,true));saveGeneral();}private void saveWebsite(){plugin.getConfig().set("websiteCustomization.initialized",true);plugin.saveConfig();WebsiteSettingsStore.load(plugin);plugin.sendServerStatus();}private void saveGeneral(){plugin.saveConfig();Main.loadConfigValues();plugin.sendServerStatus();}
    @EventHandler public void close(InventoryCloseEvent e){if(e.getPlayer() instanceof Player p)Bukkit.getScheduler().runTask(plugin,()->{if(p.getOpenInventory().getTopInventory().getSize()==p.getInventory().getSize())openPages.remove(p.getUniqueId());});}
    private void toggleItem(Inventory i,int slot,String path,String name){boolean on=plugin.getConfig().getBoolean(path,true);i.setItem(slot,state(on,name,on?"Enabled":"Disabled","Click to toggle"));}private ItemStack state(boolean on,String name,String...lore){return item(on?Material.LIME_DYE:Material.GRAY_DYE,name,lore);}private void back(Inventory i){i.setItem(45,item(Material.ARROW,"Back"));}
    private ItemStack head(Player p,String name,String...lore){ItemStack item=item(Material.PLAYER_HEAD,name,lore);if(item.getItemMeta() instanceof SkullMeta meta){meta.setOwningPlayer(p);item.setItemMeta(meta);}return item;}private ItemStack item(Material material,String name,String...lore){ItemStack item=new ItemStack(material);ItemMeta meta=item.getItemMeta();meta.displayName(Component.text(name,NamedTextColor.WHITE).decoration(TextDecoration.ITALIC,false));if(lore.length>0)meta.lore(Arrays.stream(lore).map(v->Component.text(v,NamedTextColor.GRAY).decoration(TextDecoration.ITALIC,false)).toList());meta.addItemFlags(ItemFlag.HIDE_ATTRIBUTES);item.setItemMeta(meta);return item;}
    private int index(int[] a,int v){for(int i=0;i<a.length;i++)if(a[i]==v)return i;return-1;}private String pretty(String v){return v.substring(0,1).toUpperCase()+v.substring(1);}private String currency(){return Main.economyType.equalsIgnoreCase("item")?Main.economyItem.name():Main.vaultCurrencyName;}private String format(double n){return new java.text.DecimalFormat("#,##0.##").format(n);}private String duration(long ms){long s=ms/1000;return String.format("%dd %02dh %02dm",s/86400,(s%86400)/3600,(s%3600)/60);}
}
