package me.cobbleBet.gui;

import com.google.gson.*;
import me.cobbleBet.Main;
import net.kyori.adventure.text.Component;
import net.kyori.adventure.text.format.NamedTextColor;
import net.kyori.adventure.text.format.TextDecoration;
import org.bukkit.*;
import org.bukkit.conversations.*;
import org.bukkit.entity.Player;
import org.bukkit.event.*;
import org.bukkit.event.inventory.InventoryClickEvent;
import org.bukkit.event.inventory.InventoryCloseEvent;
import org.bukkit.inventory.*;
import org.bukkit.inventory.meta.ItemMeta;
import org.jetbrains.annotations.NotNull;
import java.text.DecimalFormat;
import java.util.*;

public final class MinesController implements Listener {
    private static final DecimalFormat MONEY=new DecimalFormat("#,##0.##");
    private static final int[] TILES={10,11,12,13,14,19,20,21,22,23,28,29,30,31,32,37,38,39,40,41,46,47,48,49,50};
    private final Main plugin;private final Map<UUID,State> states=new HashMap<>();private final Map<UUID,Integer> selectedMines=new HashMap<>();private final Map<UUID,String> physicalFields=new HashMap<>();
    public MinesController(Main plugin){this.plugin=plugin;}
    public void open(Player p){physicalFields.remove(p.getUniqueId());if(!plugin.requireGameEnabled(p,"mines"))return;request(p,"open",null);State s=states.get(p.getUniqueId());if(s!=null&&s.started)renderField(p,s);else openSetup(p);}
    public void openPhysical(Player p,String fieldId){if(!plugin.requireGameEnabled(p,"mines"))return;physicalFields.put(p.getUniqueId(),fieldId);if(plugin.gamblingIndicatorManager!=null)plugin.gamblingIndicatorManager.expectPhysicalReveal(p.getUniqueId(),"mines",12L);request(p,"open",null);State s=states.get(p.getUniqueId());if(s!=null&&s.started)showState(p,s);else openSetup(p);}
    public void openSetup(Player p){if(!plugin.requireGameEnabled(p,"mines"))return;int mines=selectedMines.getOrDefault(p.getUniqueId(),3);Holder h=new Holder(Kind.SETUP);Inventory i=Bukkit.createInventory(h,45,Component.text("Mines setup 💣",NamedTextColor.DARK_GREEN));h.inventory=i;fill(i,Material.BLACK_STAINED_GLASS_PANE);i.setItem(4,item(Material.EMERALD,"Choose your stake 💰",NamedTextColor.GREEN,"Select a preset or enter a custom amount."));double[] bets={10,50,100,500,1000};for(int n=0;n<bets.length;n++)i.setItem(10+n,item(Material.GOLD_INGOT,MONEY.format(bets[n])+" 💰",NamedTextColor.GOLD,"Start with "+mines+" mines."));i.setItem(16,item(Material.NAME_TAG,"Custom bet ✏",NamedTextColor.AQUA,"Enter an amount in chat."));i.setItem(29,item(Material.RED_DYE,"Fewer mines ➖",NamedTextColor.YELLOW,"Current: "+mines));i.setItem(31,item(Material.TNT,mines+" mines 💣",NamedTextColor.RED,"More mines increase the multiplier."));i.setItem(33,item(Material.LIME_DYE,"More mines ➕",NamedTextColor.GREEN,"Maximum: 24"));i.setItem(40,item(Material.BARRIER,"Close ✖",NamedTextColor.RED));p.openInventory(i);}
    public void start(Player p,String raw,int mineCount){if(!plugin.requireGameEnabled(p,"mines"))return;if(plugin.cobbleSocketClient==null||!plugin.cobbleSocketClient.isApproved()){p.sendMessage(Component.text("CobbleBet is reconnecting. Try again shortly.",NamedTextColor.RED));return;}double bet;try{bet=Double.parseDouble(raw.replace(",",""));}catch(NumberFormatException e){p.sendMessage(Component.text("Enter a valid Mines bet.",NamedTextColor.RED));return;}if(!Double.isFinite(bet)||bet<.1||bet>1e12||mineCount<1||mineCount>24){p.sendMessage(Component.text("Use a valid bet and 1 to 24 mines.",NamedTextColor.RED));return;}selectedMines.put(p.getUniqueId(),mineCount);State s=states.computeIfAbsent(p.getUniqueId(),k->new State());s.result=null;s.mines=Set.of();s.mineAmount=mineCount;s.awaitingStart=true;JsonObject data=new JsonObject();data.addProperty("bet",bet);data.addProperty("mineAmount",mineCount);data.addProperty("clientSeed",UUID.randomUUID().toString());request(p,"start",data);p.closeInventory();p.sendActionBar(Component.text("Planting the Mines field…",NamedTextColor.GRAY));}
    public void tile(Player p,int tile){State s=states.get(p.getUniqueId());if(s==null||!s.started){p.sendMessage(Component.text("Start a Mines round first.",NamedTextColor.RED));return;}if(tile<0||tile>24)return;JsonObject data=new JsonObject();data.addProperty("tile",tile);request(p,"tile",data);}
    public void cashout(Player p){State s=states.get(p.getUniqueId());if(s==null||!s.started){p.sendMessage(Component.text("Start a Mines round first.",NamedTextColor.RED));return;}request(p,"cashout",null);p.sendActionBar(Component.text("Cashing out…",NamedTextColor.GRAY));}
    private void request(Player p,String action,JsonObject data){if(plugin.cobbleSocketClient==null||!plugin.cobbleSocketClient.isApproved()){p.sendMessage(Component.text("CobbleBet is reconnecting. Try again shortly.",NamedTextColor.RED));return;}JsonObject json=data==null?new JsonObject():data;json.addProperty("type","minesAction");json.addProperty("action",action);json.addProperty("playerUUID",p.getUniqueId().toString());json.addProperty("playerName",p.getName());plugin.cobbleSocketClient.send(json.toString());}
    public void accept(JsonObject message){if(!message.has("playerUUID")||!message.has("event"))return;UUID uuid;try{uuid=UUID.fromString(message.get("playerUUID").getAsString());}catch(RuntimeException e){return;}String event=message.get("event").getAsString();JsonObject data=message.has("data")&&message.get("data").isJsonObject()?message.getAsJsonObject("data"):new JsonObject();Bukkit.getScheduler().runTask(plugin,()->{Player p=Bukkit.getPlayer(uuid);if(p==null)return;State s=states.computeIfAbsent(uuid,k->new State());switch(event){case"error"->{s.awaitingStart=false;p.sendMessage(Component.text(data.has("message")?data.get("message").getAsString():"Mines action failed.",NamedTextColor.RED));if(!s.started)cancelPhysical(uuid);}case"balance-update"->{if(data.has("balance"))s.balance=data.get("balance").getAsDouble();}case"mines-ready"->{if(data.has("balance"))s.balance=data.get("balance").getAsDouble();}case"game-state-update"->{if(data.has("mineAmount"))s.mineAmount=data.get("mineAmount").getAsInt();if(data.has("multiplier"))s.multiplier=data.get("multiplier").getAsDouble();s.revealed=ints(data.getAsJsonArray("revealedTiles"));if(data.has("started"))s.started=data.get("started").getAsBoolean();else s.started=true;showState(p,s);}case"game-over"->{s.started=false;s.mines=new HashSet<>(ints(data.getAsJsonArray("mines")));boolean won=data.has("won")&&data.get("won").getAsBoolean();s.result=won?"Cashed out "+MONEY.format(data.get("winnings").getAsDouble()):"You hit a mine";showState(p,s);String field=physicalFields.remove(uuid);if(field!=null)plugin.minesFieldManager.finish(field,uuid,s.revealed,s.mines,s.result);p.playSound(p.getLocation(),won?Sound.ENTITY_PLAYER_LEVELUP:Sound.ENTITY_GENERIC_EXPLODE,.8f,won?1.2f:.85f);}default->{}}});}
    private void showState(Player p,State s){s.awaitingStart=false;String field=physicalFields.get(p.getUniqueId());if(field!=null){p.closeInventory();plugin.minesFieldManager.update(field,p.getUniqueId(),s.revealed,s.mines,s.multiplier,s.started,s.result);}else renderField(p,s);}
    private void renderField(Player p,State s){Holder h=new Holder(Kind.FIELD);Inventory i=Bukkit.createInventory(h,54,Component.text("Mines field 💣",NamedTextColor.DARK_GREEN));h.inventory=i;fill(i,Material.BLACK_STAINED_GLASS_PANE);i.setItem(0,item(Material.TNT,s.mineAmount+" mines 💣",NamedTextColor.RED));i.setItem(4,item(Material.GOLD_NUGGET,(s.result==null?String.format(Locale.US,"%.2f×",s.multiplier):s.result)+" 💰",s.result==null?NamedTextColor.GOLD:s.result.startsWith("Cashed")?NamedTextColor.GREEN:NamedTextColor.RED,"Balance: "+MONEY.format(s.balance)));i.setItem(8,item(Material.PLAYER_HEAD,p.getName()+" 👤",NamedTextColor.AQUA));for(int n=0;n<25;n++){boolean safe=s.revealed.contains(n),mine=s.mines.contains(n);i.setItem(TILES[n],item(mine?Material.TNT:safe?Material.EMERALD:Material.GRAY_STAINED_GLASS_PANE,mine?"Mine 💥":safe?"Safe 💎":"Hidden tile ❔",mine?NamedTextColor.RED:safe?NamedTextColor.GREEN:NamedTextColor.GRAY));}i.setItem(53,s.started?item(Material.EMERALD,"Cash out 💰",NamedTextColor.GREEN,"Current multiplier: "+String.format(Locale.US,"%.2f×",s.multiplier)):item(Material.LIME_DYE,"Play again 🔄",NamedTextColor.GREEN));p.openInventory(i);}
    private List<Integer> ints(JsonArray a){List<Integer> out=new ArrayList<>();if(a!=null)for(JsonElement e:a)try{out.add(e.getAsInt());}catch(RuntimeException ignored){}return out;}
    @EventHandler public void click(InventoryClickEvent e){if(!(e.getWhoClicked() instanceof Player p)||!(e.getView().getTopInventory().getHolder() instanceof Holder h))return;e.setCancelled(true);if(e.getClickedInventory()!=e.getView().getTopInventory())return;int slot=e.getRawSlot();if(h.kind==Kind.SETUP){int mines=selectedMines.getOrDefault(p.getUniqueId(),3);if(slot>=10&&slot<=14){double[] bets={10,50,100,500,1000};start(p,String.valueOf(bets[slot-10]),mines);}else if(slot==16)custom(p,mines);else if(slot==29){selectedMines.put(p.getUniqueId(),Math.max(1,mines-1));openSetup(p);}else if(slot==33){selectedMines.put(p.getUniqueId(),Math.min(24,mines+1));openSetup(p);}else if(slot==40)p.closeInventory();}else{int tile=index(slot);State s=states.get(p.getUniqueId());if(tile>=0&&s!=null&&s.started)tile(p,tile);else if(slot==53){if(s!=null&&s.started)cashout(p);else openSetup(p);}}}
    @EventHandler public void close(InventoryCloseEvent e){if(!(e.getPlayer() instanceof Player p)||!(e.getInventory().getHolder() instanceof Holder h)||h.kind!=Kind.SETUP)return;Bukkit.getScheduler().runTask(plugin,()->{if(p.getOpenInventory().getTopInventory().getHolder() instanceof Holder current&&current.kind==Kind.SETUP)return;State s=states.get(p.getUniqueId());if(s!=null&&(s.started||s.awaitingStart))return;cancelPhysical(p.getUniqueId());});}
    private void custom(Player p,int mines){State s=states.computeIfAbsent(p.getUniqueId(),k->new State());s.awaitingStart=true;p.closeInventory();p.sendMessage(Component.text("Type your Mines bet in chat, or type cancel.",NamedTextColor.AQUA));new ConversationFactory(plugin).withLocalEcho(false).withTimeout(30).withFirstPrompt(new StringPrompt(){@Override public @NotNull String getPromptText(@NotNull ConversationContext c){return"";}@Override public Prompt acceptInput(@NotNull ConversationContext c,String input){s.awaitingStart=false;if(!input.equalsIgnoreCase("cancel"))Bukkit.getScheduler().runTask(plugin,()->start(p,input,mines));else Bukkit.getScheduler().runTask(plugin,()->cancelPhysical(p.getUniqueId()));return END_OF_CONVERSATION;}}).buildConversation(p).begin();}
    private void cancelPhysical(UUID player){String field=physicalFields.remove(player);if(plugin.gamblingIndicatorManager!=null)plugin.gamblingIndicatorManager.cancelPhysicalReveal(player);if(field!=null)plugin.minesFieldManager.cancel(field,player);}
    private int index(int slot){for(int n=0;n<TILES.length;n++)if(TILES[n]==slot)return n;return-1;}private void fill(Inventory i,Material m){ItemStack pane=item(m," ",NamedTextColor.GRAY);for(int n=0;n<i.getSize();n++)i.setItem(n,pane);}private ItemStack item(Material m,String name,NamedTextColor color,String...lore){ItemStack s=new ItemStack(m);ItemMeta meta=s.getItemMeta();meta.displayName(Component.text(name,color).decoration(TextDecoration.ITALIC,false));if(lore.length>0)meta.lore(Arrays.stream(lore).map(v->Component.text(v,NamedTextColor.GRAY).decoration(TextDecoration.ITALIC,false)).toList());s.setItemMeta(meta);return s;}
    private enum Kind{SETUP,FIELD}private static final class Holder implements InventoryHolder{final Kind kind;Inventory inventory;Holder(Kind kind){this.kind=kind;}@Override public @NotNull Inventory getInventory(){return inventory;}}private static final class State{boolean started,awaitingStart;double balance,multiplier=1;int mineAmount=3;List<Integer>revealed=List.of();Set<Integer>mines=Set.of();String result;}
}
